language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install libboost-all-dev scons libpcre++
before_script:
  - ./buildscript/install_mongocxx.sh
script: make
branches:
  only:
    - master
notifications:
  recipients:
    - xinjiang.shao@exactsports.com
  email:
    on_success: change
    on_failure: always
