language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get install libboost-all-dev
script: make
branches:
  only:
    - master
notifications:
  recipients:
    - xinjiang.shao@exactsports.com
  email:
    on_success: change
    on_failure: always
